# FROM saarthicore114.azurecr.io/rasa114:latest
FROM 907972392184.dkr.ecr.ap-south-1.amazonaws.com/rasa114:latest

RUN pip3 install num2words
RUN pip3 install pydub
RUN apt-get -y update
RUN apt-get install -y ffmpeg
RUN pip3 install fastapi
RUN pip3 install azure
RUN pip3 install azure-cognitiveservices-speech==1.19.0
RUN pip3 install python-dotenv==0.20.0
RUN pip3 install uvicorn
COPY . /app
EXPOSE 7008
ENTRYPOINT ["/app/botstart.sh"]